name: Lesson Note RAG CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: lesson_generator_test
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u ci_user -pci_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install system dependencies (ffmpeg)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r backend/requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in $(seq 1 10); do
          mysql -h 127.0.0.1 -u ci_user -pci_password -e "SELECT 1" lesson_generator_test && break
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Run Linting
      run: |
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: ci_user
        MYSQL_PASSWORD: ci_password
        MYSQL_DATABASE: lesson_generator_test
        GEMINI_API_KEY: dummy_gemini_key
        DEEPSEEK_API_KEY: dummy_deepseek_key
      run: |
        pytest backend/tests/